import type { AgentNode, AgentEdge, AgentInfo } from '@/types';

export const NODES: AgentNode[] = [
  { id: 'orch',      label: 'ORCHESTRATOR', sub: 'core agent',   layer: 'core',     r: 44 },
  { id: 'helius',    label: 'HELIUS',       sub: 'listener',     layer: 'data',     r: 22 },
  { id: 'signal',    label: 'SIGNAL',       sub: 'collector',    layer: 'data',     r: 28 },
  { id: 'trending',  label: 'TRENDING',     sub: 'indexer',      layer: 'data',     r: 22 },
  { id: 'graduated', label: 'GRAD',         sub: 'watcher',      layer: 'data',     r: 20 },
  { id: 'enrich',    label: 'ENRICH',       sub: 'worker',       layer: 'enrich',   r: 26 },
  { id: 'oracle',    label: 'ORACLE',       sub: 'price feed',   layer: 'enrich',   r: 22 },
  { id: 'wallet',    label: 'WALLET',       sub: 'tracker',      layer: 'enrich',   r: 22 },
  { id: 'fxtwitter', label: 'FXTWITTER',    sub: 'narrative',    layer: 'enrich',   r: 20 },
  { id: 'filter',    label: 'FILTER',       sub: 'gate',         layer: 'analysis', r: 24 },
  { id: 'strategy',  label: 'STRATEGY',     sub: 'engine',       layer: 'analysis', r: 30 },
  { id: 'risk',      label: 'RISK',         sub: 'manager',      layer: 'analysis', r: 24 },
  { id: 'sentiment', label: 'SENTIMENT',    sub: 'agent',        layer: 'analysis', r: 20 },
  { id: 'llm',       label: 'LLM',          sub: 'screener',     layer: 'decision', r: 32 },
  { id: 'jup',       label: 'JUPITER',      sub: 'router',       layer: 'exec',     r: 24 },
  { id: 'exec',      label: 'EXECUTION',    sub: 'engine',       layer: 'exec',     r: 28 },
  { id: 'monitor',   label: 'POSITION',     sub: 'monitor',      layer: 'exec',     r: 26 },
  { id: 'tg',        label: 'TELEGRAM',     sub: 'interface',    layer: 'iface',    r: 26 },
  { id: 'scheduler', label: 'SCHEDULER',    sub: 'cron agent',   layer: 'iface',    r: 20 },
];

export const EDGES: AgentEdge[] = [
  { source: 'helius',    target: 'signal'   },
  { source: 'helius',    target: 'oracle'   },
  { source: 'trending',  target: 'signal'   },
  { source: 'trending',  target: 'strategy' },
  { source: 'graduated', target: 'signal'   },
  { source: 'graduated', target: 'orch'     },
  { source: 'signal',    target: 'orch'     },
  { source: 'signal',    target: 'filter'   },
  { source: 'signal',    target: 'strategy' },
  { source: 'orch',      target: 'strategy' },
  { source: 'orch',      target: 'llm'      },
  { source: 'orch',      target: 'tg'       },
  { source: 'orch',      target: 'scheduler'},
  { source: 'orch',      target: 'enrich'   },
  { source: 'tg',        target: 'orch'     },
  { source: 'scheduler', target: 'signal'   },
  { source: 'scheduler', target: 'orch'     },
  { source: 'wallet',    target: 'enrich'   },
  { source: 'wallet',    target: 'sentiment'},
  { source: 'wallet',    target: 'strategy' },
  { source: 'fxtwitter', target: 'enrich'   },
  { source: 'fxtwitter', target: 'sentiment'},
  { source: 'oracle',    target: 'strategy' },
  { source: 'oracle',    target: 'risk'     },
  { source: 'oracle',    target: 'llm'      },
  { source: 'enrich',    target: 'strategy' },
  { source: 'enrich',    target: 'llm'      },
  { source: 'enrich',    target: 'risk'     },
  { source: 'filter',    target: 'strategy' },
  { source: 'filter',    target: 'risk'     },
  { source: 'sentiment', target: 'llm'      },
  { source: 'sentiment', target: 'strategy' },
  { source: 'strategy',  target: 'llm'      },
  { source: 'strategy',  target: 'risk'     },
  { source: 'risk',      target: 'orch'     },
  { source: 'risk',      target: 'exec'     },
  { source: 'llm',       target: 'exec'     },
  { source: 'llm',       target: 'jup'      },
  { source: 'jup',       target: 'exec'     },
  { source: 'exec',      target: 'monitor'  },
  { source: 'monitor',   target: 'orch'     },
  { source: 'monitor',   target: 'risk'     },
  { source: 'monitor',   target: 'tg'       },
];

export const NODE_FULL: Record<string, string> = {
  orch:      'ORCHESTRATOR',
  helius:    'HELIUS LISTENER',
  signal:    'SIGNAL COLLECTOR',
  trending:  'TRENDING INDEXER',
  graduated: 'GRADUATED WATCHER',
  enrich:    'ENRICHMENT WORKER',
  oracle:    'PRICE ORACLE',
  wallet:    'WALLET TRACKER',
  fxtwitter: 'FXTWITTER NARRATIVE',
  filter:    'FILTER GATE',
  strategy:  'STRATEGY ENGINE',
  risk:      'RISK MANAGER',
  sentiment: 'SENTIMENT AGENT',
  llm:       'LLM SCREENER',
  jup:       'JUPITER ROUTER',
  exec:      'EXECUTION ENGINE',
  monitor:   'POSITION MONITOR',
  tg:        'TELEGRAM INTERFACE',
  scheduler: 'SCHEDULER AGENT',
};

export const AGENT_DATA: Record<string, AgentInfo> = {
  orch: {
    role: 'Central coordinator. Routes incoming candidates to strategy and LLM layers. Dispatches alerts to Telegram. Receives gate results from Risk Manager. Coordinates all 18 sub-agents.',
    connects_from: ['signal', 'monitor', 'risk', 'scheduler', 'tg', 'graduated'],
    connects_to:   ['strategy', 'llm', 'tg', 'scheduler', 'enrich'],
  },
  helius: {
    role: 'Listens to Helius WebSocket for on-chain events: fee-claim activity and graduated token alerts. Feeds real-time events to Signal Collector and Price Oracle.',
    connects_from: [],
    connects_to:   ['signal', 'oracle'],
  },
  signal: {
    role: 'Aggregates all incoming token candidates from Helius, Trending Indexer, and Graduated Watcher. Deduplicates and stores in candidates table. Dispatches to Orchestrator and Filter Gate.',
    connects_from: ['helius', 'trending', 'graduated', 'scheduler'],
    connects_to:   ['orch', 'filter', 'strategy'],
  },
  trending: {
    role: 'Polls Jupiter trending API every 60s. Returns top N tokens by volume/swaps. Feeds into Signal Collector and directly to Strategy Engine.',
    connects_from: [],
    connects_to:   ['signal', 'strategy'],
  },
  graduated: {
    role: 'Monitors Pump.fun token graduation events. Alerts Orchestrator directly and feeds Signal Collector for graduated token candidates.',
    connects_from: [],
    connects_to:   ['signal', 'orch'],
  },
  enrich: {
    role: 'GMGN enrichment worker. Fetches holder count, liquidity, top traders, and rug metrics. Rate-limited to 2500ms minimum between calls. Stores results back in candidates table.',
    connects_from: ['wallet', 'fxtwitter', 'orch'],
    connects_to:   ['strategy', 'llm', 'risk'],
  },
  oracle: {
    role: 'Fetches live price, mcap, 5m/1h/24h delta for each candidate. Uses Jupiter + Helius price feeds. Injects current market data into enriched context.',
    connects_from: ['helius'],
    connects_to:   ['strategy', 'risk', 'llm'],
  },
  wallet: {
    role: 'Cross-references token candidates against saved smart-money wallets. Detects fee-claim overlap — the core sniper signal. Managed via /walletadd and /walletremove.',
    connects_from: [],
    connects_to:   ['enrich', 'sentiment', 'strategy'],
  },
  fxtwitter: {
    role: 'Scrapes CT narrative for token contract address via FXTwitter proxy. Returns recent tweets, sentiment indicators, and influencer mention count.',
    connects_from: [],
    connects_to:   ['enrich', 'sentiment'],
  },
  filter: {
    role: 'Applies per-strategy configurable gate parameters: min source count, age range, mcap range, holder minimum, bundler rate, ATH distance. Results logged per token per strategy.',
    connects_from: ['signal'],
    connects_to:   ['strategy', 'risk'],
  },
  strategy: {
    role: 'Core strategy engine. Applies strategy-specific scoring on top of gate results. Selects the best N candidates per cycle for LLM batch submission. 4 built-in strategies.',
    connects_from: ['filter', 'enrich', 'oracle', 'wallet', 'sentiment', 'trending', 'signal', 'orch'],
    connects_to:   ['llm', 'risk'],
  },
  risk: {
    role: 'Final risk check before execution approval. Enforces position cap (MAX_OPEN_POSITIONS), bundler rate threshold, rug ratio limit. Returns gate pass/fail to Orchestrator.',
    connects_from: ['filter', 'oracle', 'enrich', 'strategy', 'monitor'],
    connects_to:   ['orch', 'exec'],
  },
  sentiment: {
    role: 'Scores CT narrative from FXTwitter and smart-money wallet quality from Wallet Tracker. Produces a 0–1 sentiment float injected into LLM context.',
    connects_from: ['wallet', 'fxtwitter'],
    connects_to:   ['llm', 'strategy'],
  },
  llm: {
    role: 'Batch LLM screener. Receives up to 10 enriched candidates per cycle with full context. Returns BUY/SKIP decisions with confidence scores. Supports any OpenAI-compatible endpoint.',
    connects_from: ['orch', 'strategy', 'enrich', 'sentiment', 'oracle'],
    connects_to:   ['exec', 'jup'],
  },
  jup: {
    role: 'Jupiter Ultra router. Selects optimal swap route for approved buy or sell. Returns route data to Execution Engine. Handles auto-slippage.',
    connects_from: ['llm'],
    connects_to:   ['exec'],
  },
  exec: {
    role: 'Execution engine. Signs and submits Jupiter Ultra swap transactions. Handles dry_run simulation, confirm-mode intent creation, and live signing. Records all trades.',
    connects_from: ['llm', 'jup', 'risk'],
    connects_to:   ['monitor'],
  },
  monitor: {
    role: 'Position monitor. Checks all open positions every 10 seconds. Fires TP, SL, trailing TP, partial TP, and max hold time logic. Sends Telegram alerts on exit events.',
    connects_from: ['exec'],
    connects_to:   ['orch', 'risk', 'tg'],
  },
  tg: {
    role: 'Telegram bot interface. Processes all commands, sends position alerts, manages confirm-mode Approve/Reject buttons. Full inline menu system for strategy and wallet management.',
    connects_from: ['orch', 'monitor'],
    connects_to:   ['orch'],
  },
  scheduler: {
    role: 'Cron agent. Triggers polling cycles at configured interval (SIGNAL_POLL_MS). Sends heartbeat to Orchestrator. Ensures consistent polling even during low-activity periods.',
    connects_from: ['orch'],
    connects_to:   ['signal', 'orch'],
  },
};
